# Generated by Django 3.0 on 2019-12-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowcharts.Flowchart')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=10)),
                ('code', models.DecimalField(decimal_places=4, max_digits=10)),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowcharts.Course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowcharts.Term')),
            ],
        ),
    ]
