# Generated by Django 3.0 on 2019-12-13 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 3, 44, 59, 698098)),
        ),
    ]
