# Generated by Django 3.0 on 2019-12-13 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0003_auto_20191213_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 4, 9, 47, 740554)),
        ),
    ]
