# Generated by Django 3.0 on 2019-12-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0005_auto_20191213_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
