# Generated by Django 3.0 on 2019-12-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0006_flowchart_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowchart',
            old_name='creates',
            new_name='created',
        ),
    ]
