# Generated by Django 3.0 on 2019-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0007_auto_20191213_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
