# Generated by Django 3.0 on 2019-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0008_auto_20191213_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
