# Generated by Django 3.0 on 2019-12-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0009_auto_20191213_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='course_slug',
        ),
        migrations.RenameField(
            model_name='flowchart',
            old_name='slug',
            new_name='flowchart_slug',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='slug',
            new_name='term_slug',
        ),
    ]
