# Generated by Django 3.0 on 2019-12-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcharts', '0010_auto_20191213_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
